# Generated by Django 4.1.2 on 2022-10-28 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('count_pages', models.IntegerField(null=True)),
                ('price', models.FloatField()),
                ('release_date', models.DateField(auto_now_add=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('photo', models.ImageField(null=True, upload_to='image/%Y/%m/%d')),
                ('exists', models.BooleanField(default=True)),
            ],
        ),
    ]
